language: node_js
yarn: true
node_js: "7"
cache:
  directories:
  - node_modules
before_deploy: 
  - chmod a+x deploy.sh
  - bash ./deploy.sh
deploy:
  skip_cleanup: true
  provider: firebase
  token:
    secure: $FIREBASE_TOKEN
  on:
    branch: master